--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-16-2023   
--------------------------------------------------------
DROP TABLE "BOOK"."BOOK" cascade constraints;
DROP TABLE "BOOK"."MEMBER" cascade constraints;
DROP TABLE "BOOK"."PURCHASE" cascade constraints;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "BOOK"."BOOK" 
   (	"BOOKNUMBER" NUMBER(10,0), 
	"BOOKNAME" VARCHAR2(50 BYTE), 
	"AUTHOR" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "BOOK"."MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONENUMBER" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"POINTS" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PURCHASE
--------------------------------------------------------

  CREATE TABLE "BOOK"."PURCHASE" 
   (	"BOOKNUMBER" NUMBER(10,0), 
	"BOOKNAME" VARCHAR2(50 BYTE), 
	"AUTHOR" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into BOOK.BOOK
SET DEFINE OFF;
Insert into BOOK.BOOK (BOOKNUMBER,BOOKNAME,AUTHOR,PRICE) values (5,'구해줘','기욤뮈소',11000);
Insert into BOOK.BOOK (BOOKNUMBER,BOOKNAME,AUTHOR,PRICE) values (1,'불편한 편의점','김호연',10000);
Insert into BOOK.BOOK (BOOKNUMBER,BOOKNAME,AUTHOR,PRICE) values (2,'새는 날아가면서 뒤돌아보지 않는다','류시화',11000);
Insert into BOOK.BOOK (BOOKNUMBER,BOOKNAME,AUTHOR,PRICE) values (3,'아낌없이 주는 나무','셸 실버스타인',12000);
Insert into BOOK.BOOK (BOOKNUMBER,BOOKNAME,AUTHOR,PRICE) values (4,'내 남자친구에게 ','귀여니',9000);
REM INSERTING into BOOK.MEMBER
SET DEFINE OFF;
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('yeri','1234','전예리','yeri@naver.com','010-1234-5678','서울시 송파구',113000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('sohi','1234','문소히','sohi@naver.com','010-1234-5678','경기도 남양주시',20000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('sanghyun','1234','김상휸','sanghyun@naver.com','010-1234-5678','서울시 송파구',40000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('dami','1234','김다미','dami@naver.com','010-1234-5678','경기도 용인시',35000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('sangwoon','1234','정상운','sangwoon@naver.com','010-1234-5678','서울시 강동구',50000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('junhang','1234','김준항','junhang@naver.com','010-1234-5678','경기도 과천시',25000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('sohyung','1234','양소형','sohyung@naver.com','010-1234-5678','서울시 송파구',60000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('mini','1234','정미니','mini@naver.com','010-1234-5678','경기도 수원시',60000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('geonyong','1234','정건용','geonyong@naver.com','010-1234-5678','경기도 남양주시',70000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('mosun','1234','강모선','mosun@naver.com','010-1234-5678','경기도 평택시',25000);
Insert into BOOK.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONENUMBER,ADDRESS,POINTS) values ('admin','admin','관리자','admin@naver.com','010-1234-5678','서울시',100000);
REM INSERTING into BOOK.PURCHASE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_PURCHASE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."PK_PURCHASE" ON "BOOK"."PURCHASE" ("BOOKNUMBER", "BOOKNAME", "AUTHOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008467
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C008467" ON "BOOK"."BOOK" ("BOOKNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008530
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C008530" ON "BOOK"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008467
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C008467" ON "BOOK"."BOOK" ("BOOKNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008530
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."SYS_C008530" ON "BOOK"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PURCHASE
--------------------------------------------------------

  CREATE UNIQUE INDEX "BOOK"."PK_PURCHASE" ON "BOOK"."PURCHASE" ("BOOKNUMBER", "BOOKNAME", "AUTHOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "BOOK"."BOOK" MODIFY ("BOOKNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."BOOK" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."BOOK" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."BOOK" ADD PRIMARY KEY ("BOOKNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "BOOK"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("PHONENUMBER" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PURCHASE
--------------------------------------------------------

  ALTER TABLE "BOOK"."PURCHASE" MODIFY ("BOOKNAME" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."PURCHASE" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."PURCHASE" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "BOOK"."PURCHASE" ADD CONSTRAINT "PK_PURCHASE" PRIMARY KEY ("BOOKNUMBER", "BOOKNAME", "AUTHOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PURCHASE
--------------------------------------------------------

  ALTER TABLE "BOOK"."PURCHASE" ADD FOREIGN KEY ("BOOKNUMBER")
	  REFERENCES "BOOK"."BOOK" ("BOOKNUMBER") ENABLE;
